name: tutorial_overlay
description: "A Flutter package for building interactive, step-by-step tutorials that highlight and point to widgets across multiple screens with customizable indicators."
version: 1.1.0
homepage: https://github.com/xinyi-chong/tutorial_overlay
repository: https://github.com/xinyi-chong/tutorial_overlay

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

topics:
  - tutorial
  - tooltip
  - overlay
  - onboarding
  - user-guide
  - walkthrough
  - widget-highlight
  - interactive-tutorial

screenshots:
  - description: 'Multi-page tutorial flow.'
    path: assets/screenshots/tutorial-across-pages.gif
  - description: 'Custom arrow indicator pointing to a button with explanatory tooltip.'
    path: assets/screenshots/custom-indicator.png
  - description: 'Tutorial without a highlighting widget.'
    path: assets/screenshots/tutorial-without-target-widget.png
  - description: 'Dynamic content update demonstrating localization support.'
    path: assets/screenshots/tutorial-update.gif