name: tutorial_overlay
description: "A Flutter package for creating interactive step-by-step tutorials with overlays."
version: 1.0.1
homepage: https://github.com/xinyi-chong/tutorial_overlay
repository: https://github.com/xinyi-chong/tutorial_overlay

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - tutorial
  - tooltip
  - overlay

screenshots:
  - description: 'This screenshot shows the tutorial steps across pages.'
    path: assets/screenshots/tutorial-across-pages.gif
  - description: 'This screenshot shows a custom indicator used during the tutorial steps.'
    path: assets/screenshots/custom-indicator.png
  - description: 'This screenshot shows the tutorial without a target widget.'
    path: assets/screenshots/tutorial-without-target-widget.png
  - description: 'This video shows the tutorial update functionality, where the tutorial content updates when the language is changed.'
    path: assets/screenshots/tutorial-update.gif